services:
    app.telegram.location.handler:
        class: AppBundle\Telegram\LocationHandler
        arguments:
            - "@doctrine_cache.providers.telegram_location_handler_cache"

    app.telegram.order.handler:
        class: AppBundle\Telegram\OrderHandler
        arguments:
            - "@doctrine_cache.providers.telegram_order_handler_cache"

    app.telegram.command.help:
        class: AppBundle\Telegram\Command\HelpCommand
        arguments:
            - "@bo_shurik_telegram_bot.command_pool"
        tags:
            - { name: bo_shurik_telegram_bot.command, priority: -512 }

    app.telegram.command.hello:
        class: AppBundle\Telegram\Command\HelloCommand
        tags:
            - { name: bo_shurik_telegram_bot.command }

    app.telegram.command.offices:
        class: AppBundle\Telegram\Command\OfficesCommand
        arguments:
            - "@app.telegram.location.handler"
            - "@app.office.repository"
        tags:
            - { name: bo_shurik_telegram_bot.command }

    app.telegram.command.order:
        class: AppBundle\Telegram\Command\OrderCommand
        arguments:
            - "@app.telegram.order.handler"
            - "@validator"
            - "@event_dispatcher"
        tags:
            - { name: bo_shurik_telegram_bot.command }
