services:
    app.telegram.command.help:
        class: AppBundle\Telegram\HelpCommand
        arguments:
            - "@bo_shurik_telegram_bot.command_pool"
        tags:
            - { name: bo_shurik_telegram_bot.command, priority: -512 }

    app.telegram.command.hello:
        class: AppBundle\Telegram\HelloCommand
        tags:
            - { name: bo_shurik_telegram_bot.command }