services:
    app.telegram.command.help:
        class: BoShurik\TelegramBotBundle\Telegram\Command\HelpCommand
        arguments:
            - "@bo_shurik_telegram_bot.command_pool"
        tags:
            - { name: bo_shurik_telegram_bot.command }

    app.telegram.command.hello:
        class: AppBundle\Telegram\HelloCommand
        tags:
            - { name: bo_shurik_telegram_bot.command }